### ISSUE TITLE
User ID for contacts

### ISSUE THREAD

**Issue by pbriggin** [clayshieh/FMF_Server#3]
Hey Clay,

To your knowledge, does this script still work? How can I find the User ID for a contact? When I put in a name, it serves me this error:

INFO:__main__:Finding user: _Nate
Traceback (most recent call last):
  File "/Users/peterbriggs/Desktop/FMF_Server-master/FMF.py", line 308, in <module>
    f.get_user_by_name("_Nate")
  File "/Users/peterbriggs/Desktop/FMF_Server-master/FMF.py", line 276, in get_user_by_name
    self.logger.debug("User {0} not in contacts or can't be found right now".format(self.contacts[user]))
KeyError: '_Nate'

The account does not have 2FA. Please advise. Thanks for your work on this!

**Comment by clayshieh** [comment]
I'll add a function to list out all current contacts so that the contact id can be used as the key
